name: '🚀 Feature Request'
description: 'Suggest an idea or enhancement for this project.'
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea! A well-defined feature request helps us understand the value it brings to the project.

  - type: checkboxes
    id: pre-flight-checks
    attributes:
      label: 'Pre-flight Checks'
      options:
        - label: 'I have searched the existing [issues](https://github.com/YOUR_USERNAME/YOUR_REPO/issues) to make sure this feature has not been requested yet.'
          required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 'Is your feature request related to a problem?'
      description: 'Please describe the problem you are trying to solve. This helps us understand the "why" behind the request.'
      placeholder: 'I am always frustrated when...'
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen.'
      placeholder: 'I would like a new button on the main dashboard that...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional Context'
      description: 'Add any other context or screenshots about the feature request here.'
