name: 'Branch Naming Rules'

on:
  push:
    branches-ignore:
      - main

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get branch name'
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: 'Check branch name'
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch_name }}"

          # Enhanced regex for conventional commit types
          REGEX="^(feature|fix|docs|style|refactor|perf|test|chore)\/.+$"

          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "Branch name '$BRANCH_NAME' is not valid."
            echo "It must start with one of: feature/, fix/, docs/, style/, refactor/, perf/, test/, chore/"
            echo "followed by a descriptive name."
            exit 1
          fi

          echo "Branch name '$BRANCH_NAME' is valid."
